"""
cron: 30 8,16 * * *
new Env('CheckinTools - V2EX 签到');
"""

# Generated by tools/sync_sites.py; do not edit directly.

from checkin_base import run_site

if __name__ == "__main__":
    raise SystemExit(run_site("v2ex"))
