"""Generate machine-owned deployment files from the canonical site catalog."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = REPO_ROOT / "src"
if str(SOURCE_ROOT) not in sys.path:
    sys.path.insert(0, str(SOURCE_ROOT))

from checkin_tools.catalog import SITE_DEFINITIONS  # noqa: E402

GENERATED_MARKER = "# Generated by tools/sync_sites.py; do not edit directly."


def _replace_block(content: str, start: str, end: str, body: str) -> str:
    if content.count(start) != 1 or content.count(end) != 1:
        raise RuntimeError(f"managed block markers are missing or duplicated: {start}")
    prefix, remainder = content.split(start, 1)
    _, suffix = remainder.split(end, 1)
    return f"{prefix}{start}\n{body.rstrip()}\n{end}{suffix}"


def _quoted(value: str) -> str:
    return "'" + value.replace("'", "\\'") + "'"


def render_qinglong_env() -> str:
    lines = [
        GENERATED_MARKER,
        "# CheckinTools 青龙集中配置模板",
        "# 订阅首次复制本模板；后续更新只向持久化配置追加缺失字段，不覆盖已有值。",
        "# 请在青龙“配置文件”中编辑复制后的文件，不要编辑仓库目录中的本文件。",
        "# 多账号使用字面量 \\n 分隔；同站点的凭据必须按相同行号对应。",
        "",
    ]
    for definition in SITE_DEFINITIONS:
        lines.append(f"# ── {definition.display_name} " + "─" * 60)
        lines.extend(f"{env_key}=''" for env_key in definition.credentials.values())
        lines.append("")

    lines.append("# ── 站点地址 " + "─" * 58)
    lines.extend(
        f"{definition.base_url_key}={_quoted(definition.base_url)}"
        for definition in SITE_DEFINITIONS
    )
    lines.extend(
        [
            "",
            "# ── 网络请求 " + "─" * 58,
            "CHECKIN_TIMEOUT_SECONDS='20'",
            "CHECKIN_RETRIES='2'",
            "",
            "# ── 通知 " + "─" * 62,
            "DINGTALK_ACCESS_TOKEN=''",
            "DINGTALK_SECRET=''",
            "FEISHU_WEBHOOK=''",
            "FEISHU_SECRET=''",
            "# auto、all、dingtalk 或 feishu",
            "CHECKIN_NOTIFY_CHANNEL='auto'",
            "# summary 或 individual",
            "CHECKIN_NOTIFY_MODE='summary'",
            "",
            "# ── 青龙持久化状态 " + "─" * 52,
            "CHECKIN_QINGLONG_DATA_DIR='/ql/data/checkin-tools'",
            "",
        ]
    )
    return "\n".join(lines)


def render_qinglong_task(site_id: str) -> str:
    definition = next(item for item in SITE_DEFINITIONS if item.id == site_id)
    task_name = f"CheckinTools - {definition.display_name} 签到"
    return f'''"""
cron: {definition.qinglong_cron}
new Env('{task_name}');
"""

{GENERATED_MARKER}

from checkin_base import run_site

if __name__ == "__main__":
    raise SystemExit(run_site("{definition.id}"))
'''


def render_actions_options() -> str:
    return "\n".join(
        ["          - all", *(f"          - {item.id}" for item in SITE_DEFINITIONS)]
    )


def render_actions_secrets() -> str:
    return "\n".join(
        f"          {env_key}: ${{{{ secrets.{env_key} }}}}"
        for definition in SITE_DEFINITIONS
        for env_key in definition.credentials.values()
    )


def _managed_actions(repo_root: Path) -> dict[Path, str]:
    path = repo_root / ".github" / "workflows" / "checkin.yml"
    if not path.is_file():
        return {}
    content = path.read_text(encoding="utf-8")
    content = _replace_block(
        content,
        "          # BEGIN GENERATED: actions-site-options",
        "          # END GENERATED: actions-site-options",
        render_actions_options(),
    )
    content = _replace_block(
        content,
        "          # BEGIN GENERATED: actions-site-secrets",
        "          # END GENERATED: actions-site-secrets",
        render_actions_secrets(),
    )
    return {path: content}


def generated_files(repo_root: Path = REPO_ROOT) -> dict[Path, str]:
    files = {repo_root / "qinglong" / "checkin-tools.env": render_qinglong_env()}
    task_dir = repo_root / "qinglong" / "DefaultTasks"
    files.update(
        {
            task_dir / f"checkin_task_{definition.id}.py": render_qinglong_task(
                definition.id
            )
            for definition in SITE_DEFINITIONS
        }
    )
    files.update(_managed_actions(repo_root))
    return files


def _stale_generated_tasks(repo_root: Path, expected: set[Path]) -> list[Path]:
    task_dir = repo_root / "qinglong" / "DefaultTasks"
    stale = []
    for path in task_dir.glob("checkin_task_*.py"):
        if path not in expected and GENERATED_MARKER in path.read_text(encoding="utf-8"):
            stale.append(path)
    return stale


def sync_sites(repo_root: Path = REPO_ROOT, *, check: bool = False) -> tuple[Path, ...]:
    files = generated_files(repo_root)
    changed = [
        path
        for path, content in files.items()
        if not path.is_file() or path.read_text(encoding="utf-8") != content
    ]
    stale = _stale_generated_tasks(repo_root, set(files))
    differences = tuple((*changed, *stale))
    if check:
        return differences

    for path in changed:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(files[path], encoding="utf-8", newline="\n")
    for path in stale:
        path.unlink()
    return differences


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report drift without writing")
    args = parser.parse_args(argv)
    differences = sync_sites(check=args.check)
    if differences:
        action = "out of date" if args.check else "updated"
        for path in differences:
            print(f"{action}: {path.relative_to(REPO_ROOT)}")
        return 1 if args.check else 0
    print("site-generated files are up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
